### ISSUE TITLE
Build compile errors etc

### ISSUE THREAD

**Issue by 0xfffffffa** [vile/web3-more-bundlers#1]
HI, 

Your package is super promising however, i've encountered so many issues installing it with dependancies not working and web3 breaking. 

`(env) chris@chriss-MacBook-Pro-2 % pip3 install web3morebundlers 
Collecting web3morebundlers
  Using cached web3morebundlers-0.1.1-py3-none-any.whl.metadata (3.8 kB)
Collecting flashbots<2.0.0,>=1.1.1 (from web3morebundlers)
  Using cached flashbots-1.1.1-py3-none-any.whl.metadata (2.2 kB)
Collecting web3<6.0.0,>=5.22.0 (from web3morebundlers)
  Using cached web3-5.31.4-py3-none-any.whl.metadata (6.1 kB)
Collecting aiohttp<4,>=3.7.4.post0 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Downloading aiohttp-3.10.6-cp312-cp312-macosx_11_0_arm64.whl.metadata (7.6 kB)
Collecting eth-abi<3.0.0,>=2.2.0 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_abi-2.2.0-py3-none-any.whl.metadata (5.9 kB)
Collecting eth-account<0.6.0,>=0.5.9 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_account-0.5.9-py3-none-any.whl.metadata (6.1 kB)
Collecting eth-hash<1.0.0,>=0.2.0 (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_hash-0.7.0-py3-none-any.whl.metadata (5.4 kB)
Collecting eth-rlp<0.3 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_rlp-0.2.1-py3-none-any.whl.metadata (5.3 kB)
Collecting eth-typing<3.0.0,>=2.0.0 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_typing-2.3.0-py3-none-any.whl.metadata (5.3 kB)
Collecting eth-utils<2.0.0,>=1.9.5 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_utils-1.10.0-py3-none-any.whl.metadata (5.8 kB)
Collecting hexbytes<1.0.0,>=0.1.0 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached hexbytes-0.3.1-py3-none-any.whl.metadata (5.5 kB)
Collecting ipfshttpclient==0.8.0a2 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl.metadata (11 kB)
Collecting jsonschema<5,>=3.2.0 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting lru-dict<2.0.0,>=1.1.6 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached lru_dict-1.3.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.5 kB)
Collecting protobuf==3.19.5 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached protobuf-3.19.5-py2.py3-none-any.whl.metadata (828 bytes)
Collecting requests<3.0.0,>=2.16.0 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting websockets<10,>=9.1 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached websockets-9.1-cp312-cp312-macosx_14_0_arm64.whl
Collecting multiaddr>=0.0.7 (from ipfshttpclient==0.8.0a2->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached multiaddr-0.0.9-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp<4,>=3.7.4.post0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached aiohappyeyeballs-2.4.0-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4,>=3.7.4.post0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.7.4.post0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.4.post0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached frozenlist-1.4.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.4.post0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached multidict-6.1.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (5.0 kB)
Collecting yarl<2.0,>=1.12.0 (from aiohttp<4,>=3.7.4.post0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached yarl-1.12.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (49 kB)
Collecting parsimonious<0.9.0,>=0.8.0 (from eth-abi<3.0.0,>=2.2.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached parsimonious-0.8.1-py3-none-any.whl
Collecting bitarray<3,>=1.2.1 (from eth-account<0.6.0,>=0.5.9->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached bitarray-2.9.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (34 kB)
Collecting eth-keyfile<0.6.0,>=0.5.0 (from eth-account<0.6.0,>=0.5.9->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_keyfile-0.5.1-py3-none-any.whl.metadata (7.3 kB)
Collecting eth-keys<0.4.0,>=0.3.4 (from eth-account<0.6.0,>=0.5.9->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_keys-0.3.4-py3-none-any.whl.metadata (12 kB)
Collecting rlp<3,>=1.0.0 (from eth-account<0.6.0,>=0.5.9->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached rlp-2.0.1-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting pycryptodome<4,>=3.6.6 (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached pycryptodome-3.20.0-cp35-abi3-macosx_10_9_universal2.whl.metadata (3.4 kB)
INFO: pip is looking at multiple versions of eth-utils to determine which version is compatible with other requirements. This could take a while.
Collecting eth-utils<2.0.0,>=1.9.5 (from web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached eth_utils-1.9.5-py3-none-any.whl.metadata (4.9 kB)
Collecting cytoolz<1.0.0,>=0.10.1 (from eth-utils<2.0.0,>=1.9.5->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached cytoolz-0.12.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.6 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema<5,>=3.2.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema<5,>=3.2.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema<5,>=3.2.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached rpds_py-0.20.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.2 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.16.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.16.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.16.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.16.0->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting toolz>=0.8.0 (from cytoolz<1.0.0,>=0.10.1->eth-utils<2.0.0,>=1.9.5->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)
Collecting varint (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached varint-1.0.2-py3-none-any.whl
Collecting six (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting base58 (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached base58-2.1.1-py3-none-any.whl.metadata (3.1 kB)
Collecting netaddr (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3<6.0.0,>=5.22.0->web3morebundlers)
  Using cached netaddr-1.3.0-py3-none-any.whl.metadata (5.0 kB)
Using cached web3morebundlers-0.1.1-py3-none-any.whl (5.2 kB)
Using cached flashbots-1.1.1-py3-none-any.whl (10 kB)
Using cached web3-5.31.4-py3-none-any.whl (502 kB)
Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
Using cached protobuf-3.19.5-py2.py3-none-any.whl (162 kB)
Downloading aiohttp-3.10.6-cp312-cp312-macosx_11_0_arm64.whl (390 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.5/390.5 kB 99.2 kB/s eta 0:00:00
Using cached eth_abi-2.2.0-py3-none-any.whl (28 kB)
Using cached eth_account-0.5.9-py3-none-any.whl (101 kB)
Using cached eth_hash-0.7.0-py3-none-any.whl (8.7 kB)
Using cached eth_rlp-0.2.1-py3-none-any.whl (5.0 kB)
Using cached eth_typing-2.3.0-py3-none-any.whl (6.2 kB)
Using cached eth_utils-1.9.5-py3-none-any.whl (23 kB)
Using cached hexbytes-0.3.1-py3-none-any.whl (5.9 kB)
Using cached jsonschema-4.23.0-py3-none-any.whl (88 kB)
Using cached lru_dict-1.3.0-cp312-cp312-macosx_11_0_arm64.whl (11 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached aiohappyeyeballs-2.4.0-py3-none-any.whl (12 kB)
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
Using cached bitarray-2.9.2-cp312-cp312-macosx_11_0_arm64.whl (124 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl (119 kB)
Using cached cytoolz-0.12.3-cp312-cp312-macosx_11_0_arm64.whl (401 kB)
Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Using cached eth_keys-0.3.4-py3-none-any.whl (21 kB)
Using cached frozenlist-1.4.1-cp312-cp312-macosx_11_0_arm64.whl (51 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Using cached multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
Using cached multidict-6.1.0-cp312-cp312-macosx_11_0_arm64.whl (29 kB)
Using cached pycryptodome-3.20.0-cp35-abi3-macosx_10_9_universal2.whl (2.4 MB)
Using cached referencing-0.35.1-py3-none-any.whl (26 kB)
Using cached rlp-2.0.1-py2.py3-none-any.whl (20 kB)
Using cached rpds_py-0.20.0-cp312-cp312-macosx_11_0_arm64.whl (313 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached yarl-1.12.1-cp312-cp312-macosx_11_0_arm64.whl (112 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached toolz-0.12.1-py3-none-any.whl (56 kB)
Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
Using cached netaddr-1.3.0-py3-none-any.whl (2.3 MB)
Installing collected packages: varint, bitarray, websockets, urllib3, toolz, six, rpds-py, pycryptodome, protobuf, netaddr, multidict, lru-dict, idna, hexbytes, frozenlist, eth-typing, eth-hash, charset-normalizer, certifi, base58, attrs, aiohappyeyeballs, yarl, requests, referencing, parsimonious, multiaddr, cytoolz, aiosignal, jsonschema-specifications, ipfshttpclient, eth-utils, aiohttp, rlp, jsonschema, eth-keys, eth-abi, eth-rlp, eth-keyfile, eth-account, web3, flashbots, web3morebundlers
Successfully installed aiohappyeyeballs-2.4.0 aiohttp-3.10.6 aiosignal-1.3.1 attrs-24.2.0 base58-2.1.1 bitarray-2.9.2 certifi-2024.8.30 charset-normalizer-3.3.2 cytoolz-0.12.3 eth-abi-2.2.0 eth-account-0.5.9 eth-hash-0.7.0 eth-keyfile-0.5.1 eth-keys-0.3.4 eth-rlp-0.2.1 eth-typing-2.3.0 eth-utils-1.9.5 flashbots-1.1.1 frozenlist-1.4.1 hexbytes-0.3.1 idna-3.10 ipfshttpclient-0.8.0a2 jsonschema-4.23.0 jsonschema-specifications-2023.12.1 lru-dict-1.3.0 multiaddr-0.0.9 multidict-6.1.0 netaddr-1.3.0 parsimonious-0.8.1 protobuf-3.19.5 pycryptodome-3.20.0 referencing-0.35.1 requests-2.32.3 rlp-2.0.1 rpds-py-0.20.0 six-1.16.0 toolz-0.12.1 urllib3-2.2.3 varint-1.0.2 web3-5.31.4 web3morebundlers-0.1.1 websockets-9.1 yarl-1.12.1

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
(env) chris@chriss-MacBook-Pro-2 frontrun % python3 main.py 
Traceback (most recent call last):
  File "/Users/chris/Desktop/Development/frontrun/main.py", line 2, in <module>
    from kill_bot.kill import Kill
  File "/Users/chris/Desktop/Development/frontrun/kill_bot/kill.py", line 2, in <module>
    from web3 import Web3
  File "/Users/chris/Desktop/Development/frontrun/env/lib/python3.12/site-packages/web3/__init__.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(env) chris@chriss-MacBook-Pro-2 % `

And from there on we go into a very very long rabbit hole that we never get out of... any solutions ?

**Comment by vile** [comment]
Hi,

I could have sworn they included multi-builder support as a feature when they updated the package to use web3py >=6.0. Flashbots is a bit notorious for slowly updating the official python package, so, I will consider updating this package to fix these issues. Otherwise, in the meantime, go support flashbots/web3-flashbots#100 and flashbots/web3-flashbots#98 so they have a push to add this natively.

**Comment by vile** [comment]
Also, for your issue specifically, I would check out [this Stackoverflow](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources) thread since your root error is `ModuleNotFoundError: No module named 'pkg_resources'`.
